### ISSUE TITLE
When does packet callback get called?

### ISSUE THREAD

**Issue by alexanderturner** [ganehag/isotp#2]
More of a question than an issue. When does callback get called and whats the expected output payload uint8 pointer in the callback function?

**Comment by ganehag** [comment]
It gets called here: (as canCallback)
https://github.com/ganehag/cantt/blob/master/src/cantt.cpp#L290
and here:
https://github.com/ganehag/cantt/blob/master/src/cantt.cpp#L344

The `uint8_t *payload` is whatever you want it to be. That's why there is a `payload_len`.

**Comment by alexanderturner** [comment]
I came here to answer and close this myself, thanks heaps @ganehag!
